### ISSUE TITLE
Android studio - TFVC - java.lang.IllegalStateException: workingFolder.localItem must not be null

### ISSUE THREAD

**Issue by rajeshaz09** [JetBrains/team-explorer-everywhere#23]
I configuring TFVC version control in Adnroid Studio. If I do "Update Directory" using TFVC-->Update Directory, I am getting following error
`Error:java.util.concurrent.ExecutionException: com.jetbrains.rd.util.reactive.RdFault: workingFolder.localItem must not be null, reason: java.lang.IllegalStateException: workingFolder.localItem must not be null
	at com.microsoft.tfs.TfsClient$Companion.loadMappings(TfsClient.kt:61)
	at com.microsoft.tfs.TfsClient$Companion.getDetailedWorkspaceInfo(TfsClient.kt:89)
	at com.microsoft.tfs.MainKt$initializeModel$3.invoke(Main.kt:100)
	at com.microsoft.tfs.MainKt$initializeModel$3.invoke(Main.kt)
	at com.jetbrains.rd.framework.impl.RdEndpoint$set$2.invoke(RdTask.kt:203)
	at com.jetbrains.rd.framework.impl.RdEndpoint$set$2.invoke(RdTask.kt:176)
	at com.jetbrains.rd.framework.impl.RdEndpoint.onWireReceived(RdTask.kt:226)
	at com.jetbrains.rd.framework.MessageBroker$invoke$1.invoke(MessageBroker.kt:31)
	at com.jetbrains.rd.framework.MessageBroker$invoke$1.invoke(MessageBroker.kt:14)
	at com.jetbrains.rd.util.threading.SingleThreadSchedulerBase$queue$1.run(SingleThreadScheduler.kt:41)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)`

**Comment by ForNeVeR** [comment]
This is not the right repo to report this, since there's no `com.microsoft.tfs.TfsClient$Companion.loadMappings` in this repository.

Please take a look/follow the investigation questions at https://github.com/microsoft/azure-devops-intellij/issues/462.
